version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
        environment:
          DATABASE_URL_TEST: postgres://test_user@localhost:5432/test_db
          IS_CIRCLE_CI: true
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
          POSTGRES_PASSWORD: ""
      - image: selenium/standalone-chrome:3.1.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v3-dependencies-

      - run: CFLAGS=-std=gnu11 yarn install

      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}

      - run: yarn build
      - run: yarn test
      - run: yarn run integration
